"""Add ErrorLog and ReviewItem

Revision ID: 703a635333a5
Revises: 
Create Date: 2026-08-08 17:51:36.559994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703a635333a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('exercise_type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.create_index('idx_user_topic_prompt', ['user_id', 'topic_id', 'prompt'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('exercise_type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', 'exercise_type', 'prompt', name='uq_review_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_queue')
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.drop_index('idx_user_topic_prompt')

    op.drop_table('error_log')
    # ### end Alembic commands ###
